name: Build llama factory image

on:
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - uses: actions/checkout@v4
        with:
          repository: hiyouga/LLaMA-Factory
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Login to the dockerhub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.KUBEAGI_DOCKER_USERNAME }}
          password: ${{ secrets.KUBEAGI_DOCKER_TOKEN }}
      - name: Build llama factory image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            kubeagi/llama-factory:latest
          push: true 
    
