name: Sync and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  sync_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Sync Script
        env:
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          ./sync.sh