name: Sync and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  sync_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Sync Script
        env:
            DOCKER_TOKEN: ${{ secrets.HARBOR_TOKEN }}
        run: |
          ./sync.sh